const movieRatings = {
  "G": "General Audiences - Suitable for all ages",
  "PG": "Parental Guidance Suggested - Some material may not be suitable for children",
  "PG-13": "Parents Strongly Cautioned - Some material may be inappropriate for children under 13",
  "R": "Restricted - Under 17 requires accompanying parent or adult guardian",
  "NC-17": "No Children 17 and Under Admitted - Explicit content, not suitable for anyone under 18",
  "U": "Universal - Suitable for all ages",
  "12A": "12A - Suitable for children 12 and older; under 12 allowed with an adult",
  "12": "12 - Suitable only for 12 years and older",
  "15": "15 - Suitable only for 15 years and older",
  "18": "18 - Suitable only for adults",
  "UA": "Parental Guidance - Suitable for all ages, but parental guidance suggested for children below 12",
  "A": "Adult - Suitable only for adults (18+)",
  "S": "Special - Restricted to specific professionals or groups",
  "M": "Mature - Recommended for ages 15 and above",
  "MA15+": "Restricted - Not suitable for children under 15 unless accompanied by an adult",
  "R18+": "Restricted - Restricted to adults 18 and older",
  "X18+": "Explicit Adult Content - Restricted to certain areas",
  "14A": "14A - Suitable for 14 years and older; under 14 requires an adult",
  "18A": "18A - Suitable for 18 years and older; under 18 requires an adult",
  "3+": "3+ - Suitable for ages 3 and older",
  "7+": "7+ - Suitable for ages 7 and older",
  "12+": "12+ - Suitable for ages 12 and older",
  "16+": "16+ - Suitable for ages 16 and older",
  "18+": "18+ - Suitable for ages 18 and older",
  "NR": "Not Rated !",
  "U/A 13+": "content is suitable for audiences aged 13 and older. However, parental guidance is advised for viewers under the age of 13"
};

export default movieRatings;
